"""votes s table

Revision ID: b79b5c87b0b1
Revises: b013a7fc80d2
Create Date: 2019-05-08 11:32:05.184674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79b5c87b0b1'
down_revision = 'b013a7fc80d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=140), nullable=True),
    sa.Column('metric', sa.String(length=140), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['metric'], ['results.metric'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alpha_character', sa.String(length=140), nullable=True),
    sa.Column('beta_character', sa.String(length=140), nullable=True),
    sa.Column('metric', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_alpha_character'), 'votes', ['alpha_character'], unique=False)
    op.create_index(op.f('ix_votes_beta_character'), 'votes', ['beta_character'], unique=False)
    op.create_index(op.f('ix_votes_metric'), 'votes', ['metric'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_metric'), table_name='votes')
    op.drop_index(op.f('ix_votes_beta_character'), table_name='votes')
    op.drop_index(op.f('ix_votes_alpha_character'), table_name='votes')
    op.drop_table('votes')
    op.drop_table('polls')
    op.drop_table('results')
    # ### end Alembic commands ###
